services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 77.88.8.8
    extra_hosts:
      - "api.telegram.org:149.154.166.110"  # Явный IP
      - "api.telegram.org:149.154.167.220"  # Резервный IP
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"