services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    network_mode: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"